export type Review = {
  name: string;
  location: string;
  rating: number;
  date: string;
  text: string;
  verified: boolean;
};

export type Product = {
  id: string;
  name: string;
  subtitle: string;
  price: number;
  comparePrice: number | null;
  badge: string | null;
  badgeColor: "violet" | "gold" | "sale" | "bundle" | null;
  rating: number;
  reviewCount: number;
  category: "serums" | "moisturisers" | "treatments" | "gift-sets";
  shortDescription: string;
  description: string;
  ingredients: string;
  howToUse: string;
  benefits: string[];
  skinType: string[];
  volume: string[];
  gradient: string;
  inStock: boolean;
  isNew: boolean;
  isSale: boolean;
  reviews: Review[];
};

export const products: Product[] = [
  {
    id: "glow-serum",
    name: "Lumina Glow Serum",
    subtitle: "30ml · Brightening Formula",
    price: 89,
    comparePrice: 110,
    badge: "Best Seller",
    badgeColor: "violet",
    rating: 4.9,
    reviewCount: 847,
    category: "serums",
    shortDescription: "Clinically proven to improve skin radiance by 67% in 4 weeks.",
    description: "A potent brightening serum powered by stabilised Vitamin C 15%, Niacinamide 5% and rare Bakuchiol extract. Visibly reduces dark spots, uneven skin tone and dullness within 28 days. Lightweight, fast-absorbing formula suitable for all skin types including sensitive.",
    ingredients: "Aqua, Ascorbic Acid (Vitamin C) 15%, Niacinamide 5%, Bakuchiol 1%, Sodium Hyaluronate, Rosa Canina Fruit Oil, Tocopherol (Vitamin E), Panthenol (Vitamin B5), Glycerin, Xanthan Gum, Citric Acid",
    howToUse: "Apply 3–4 drops to clean skin every morning before moisturiser and SPF. Can also be used in evening routine. Avoid direct contact with eyes. Patch test recommended for first-time use.",
    benefits: ["Reduces dark spots in 28 days", "Boosts radiance by 67%", "Evens skin tone", "Lightweight & fast-absorbing"],
    skinType: ["Normal", "Dry", "Combination", "Sensitive"],
    volume: ["15ml", "30ml", "50ml"],
    gradient: "from-[#1A0A2E] via-[#2D1854] to-[#C97B3A]",
    inStock: true,
    isNew: false,
    isSale: false,
    reviews: [
      { name: "Sarah M.", location: "London, UK", rating: 5, date: "2 weeks ago", text: "Transformed my skin in just 3 weeks. My hyperpigmentation has visibly faded and my skin genuinely looks lit from within. I've repurchased twice already.", verified: true },
      { name: "Priya K.", location: "Dubai, UAE", rating: 5, date: "1 month ago", text: "Best serum I've ever used. The texture is so lightweight and it layers perfectly under my moisturiser. Visible results from week two.", verified: true },
      { name: "Emma L.", location: "New York, USA", rating: 5, date: "3 weeks ago", text: "My dull winter skin is completely transformed. I look genuinely radiant. Worth every penny.", verified: true },
      { name: "Aisha T.", location: "Toronto, CA", rating: 4, date: "1 month ago", text: "Really impressive results on my dark spots. Took about 4 weeks to see full effect but the improvement is undeniable.", verified: true },
      { name: "Mei L.", location: "Singapore", rating: 5, date: "2 months ago", text: "Repurchasing for the third time. This is now a permanent part of my routine.", verified: true },
      { name: "Olivia R.", location: "Sydney, AU", rating: 5, date: "3 months ago", text: "I was sceptical but the results speak for themselves. My skin has never looked better.", verified: true },
    ],
  },
  {
    id: "velvet-cream",
    name: "Velvet Moisture Cream",
    subtitle: "50ml · Deep Hydration",
    price: 72,
    comparePrice: null,
    badge: "New",
    badgeColor: "gold",
    rating: 4.8,
    reviewCount: 512,
    category: "moisturisers",
    shortDescription: "72-hour deep hydration with Ceramide Complex and Snow Mushroom.",
    description: "A rich yet weightless moisturiser that delivers 72-hour hydration. Formulated with a triple Ceramide Complex, rare Snow Mushroom extract and Squalane to restore the skin barrier, lock in moisture and deliver a visibly plumped, luminous complexion from first use.",
    ingredients: "Aqua, Squalane, Ceramide NP, Ceramide AP, Ceramide EOP, Tremella Fuciformis Sporocarp Extract (Snow Mushroom), Glycerin, Butyrospermum Parkii (Shea Butter), Peptide Complex, Niacinamide 3%, Allantoin, Carbomer",
    howToUse: "Apply morning and evening to clean face and neck after serum. Take a pearl-sized amount, warm between fingertips and press gently into skin. Suitable for all skin types including sensitive skin.",
    benefits: ["72-hour hydration", "Restores skin barrier", "Visibly plumps skin", "Suitable for sensitive skin"],
    skinType: ["Normal", "Dry", "Sensitive", "Mature"],
    volume: ["30ml", "50ml"],
    gradient: "from-[#2D1854] via-[#4A1F7A] to-[#C97B3A]",
    inStock: true,
    isNew: true,
    isSale: false,
    reviews: [
      { name: "Charlotte B.", location: "Paris, FR", rating: 5, date: "1 week ago", text: "The texture is extraordinary — rich but not heavy at all. My skin drinks it up and stays hydrated all day long.", verified: true },
      { name: "Natasha V.", location: "Moscow, RU", rating: 5, date: "3 weeks ago", text: "My dry patches have completely disappeared. This is genuinely the best moisturiser I have ever used.", verified: true },
      { name: "Fatima A.", location: "Riyadh, SA", rating: 4, date: "1 month ago", text: "Beautiful cream, very luxurious. Sits well under makeup without pilling. Highly recommend.", verified: true },
      { name: "Zoe H.", location: "Melbourne, AU", rating: 5, date: "1 month ago", text: "Finally found a moisturiser that actually works on my dry skin. Remarkable results.", verified: true },
      { name: "Isabel M.", location: "Madrid, ES", rating: 5, date: "2 months ago", text: "Worth the price. My skin looks and feels completely different after 4 weeks.", verified: true },
      { name: "Hannah K.", location: "Berlin, DE", rating: 5, date: "2 months ago", text: "Silky, effective, luxurious. Perfect for winter skin.", verified: true },
    ],
  },
  {
    id: "eye-elixir",
    name: "Rose Gold Eye Elixir",
    subtitle: "15ml · Anti-Ageing",
    price: 58,
    comparePrice: 75,
    badge: "Sale",
    badgeColor: "sale",
    rating: 4.7,
    reviewCount: 334,
    category: "serums",
    shortDescription: "Reduces dark circles, puffiness and fine lines in 14 days.",
    description: "A luxurious eye treatment that visibly reduces dark circles, puffiness and fine lines around the delicate eye area. Formulated with Retinol Alternative Bakuchiol, Caffeine 2%, Colloidal Gold particles and a Tri-Peptide Complex for visible lifting and brightening from week two.",
    ingredients: "Aqua, Bakuchiol 0.5%, Caffeine 2%, Colloidal Gold, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Sodium Hyaluronate, Centella Asiatica Extract, Tocopherol",
    howToUse: "Gently pat 1–2 drops around the entire orbital bone morning and evening using your ring finger. Never rub or pull the skin. Use before moisturiser. Suitable for contact lens wearers.",
    benefits: ["Reduces dark circles", "Depuffs in minutes", "Firms and lifts", "Gentle enough for contact lens wearers"],
    skinType: ["All skin types", "Mature", "Sensitive"],
    volume: ["15ml"],
    gradient: "from-[#1A0A2E] via-[#4A1F7A] to-[#E8A060]",
    inStock: true,
    isNew: false,
    isSale: true,
    reviews: [
      { name: "Emma L.", location: "New York, USA", rating: 5, date: "2 weeks ago", text: "I was sceptical about eye creams until this. Within two weeks my dark circles were noticeably lighter. Remarkable.", verified: true },
      { name: "Diane W.", location: "Chicago, USA", rating: 5, date: "1 month ago", text: "I travel constantly and this saves my eyes every time. Puffiness is gone within minutes of applying.", verified: true },
      { name: "Yuki S.", location: "Tokyo, JP", rating: 4, date: "1 month ago", text: "Very gentle and effective. No irritation at all around my sensitive eyes.", verified: true },
      { name: "Rosa P.", location: "Milan, IT", rating: 5, date: "2 months ago", text: "Incredibly luxurious eye treatment. The gold particles make it feel so special.", verified: true },
      { name: "Lena B.", location: "Stockholm, SE", rating: 5, date: "2 months ago", text: "My under-eyes look 5 years younger. No exaggeration.", verified: true },
      { name: "Amelia J.", location: "Cape Town, ZA", rating: 4, date: "3 months ago", text: "Good results on fine lines. Takes about 3 weeks to see the full effect but worth the wait.", verified: true },
    ],
  },
  {
    id: "clay-masque",
    name: "Purifying Clay Masque",
    subtitle: "75ml · Deep Cleanse",
    price: 45,
    comparePrice: null,
    badge: "Popular",
    badgeColor: "violet",
    rating: 4.8,
    reviewCount: 621,
    category: "treatments",
    shortDescription: "Deep pore cleansing with Kaolin, Charcoal and Tea Tree.",
    description: "A deeply detoxifying clay masque that draws out impurities, visibly minimises pores and controls excess sebum without stripping moisture. Kaolin and Bentonite clay combined with Activated Charcoal and Tea Tree Oil for a thorough, clarifying cleanse that leaves skin smooth and refined.",
    ingredients: "Kaolin, Bentonite, Aqua, Activated Charcoal, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Salicylic Acid 0.5%, Aloe Barbadensis Leaf Juice, Glycerin, Allantoin",
    howToUse: "Apply a thin, even layer to clean dry skin 2–3 times per week avoiding the eye area. Leave for 10–15 minutes until dry. Rinse thoroughly with warm water. Follow with toner and moisturiser.",
    benefits: ["Minimises pores", "Controls excess oil", "Removes impurities", "Leaves skin smooth"],
    skinType: ["Oily", "Combination", "Acne-prone", "Normal"],
    volume: ["75ml"],
    gradient: "from-[#2D1854] via-[#1A0A2E] to-[#4A1F7A]",
    inStock: true,
    isNew: false,
    isSale: false,
    reviews: [
      { name: "Jasmine T.", location: "Los Angeles, USA", rating: 5, date: "1 week ago", text: "My pores look so much smaller after using this twice a week. It actually works.", verified: true },
      { name: "Chloe N.", location: "Seoul, KR", rating: 5, date: "2 weeks ago", text: "Perfect for my oily T-zone. Controls oil all day after use. Repurchasing immediately.", verified: true },
      { name: "Sophie G.", location: "London, UK", rating: 5, date: "1 month ago", text: "The best clay mask I have used. My skin feels genuinely purified and refined afterwards.", verified: true },
      { name: "Mia F.", location: "Amsterdam, NL", rating: 4, date: "1 month ago", text: "Very effective. My breakouts have reduced significantly since using this weekly.", verified: true },
      { name: "Anya R.", location: "Mumbai, IN", rating: 5, date: "2 months ago", text: "Holy grail product for combination skin. Removes blackheads and controls shine perfectly.", verified: true },
      { name: "Lily C.", location: "Hong Kong", rating: 5, date: "2 months ago", text: "Skin feels like glass after. Best masque at this price point.", verified: true },
    ],
  },
  {
    id: "silk-toner",
    name: "Silk Exfoliating Toner",
    subtitle: "150ml · Radiance",
    price: 38,
    comparePrice: null,
    badge: "Popular",
    badgeColor: "violet",
    rating: 4.6,
    reviewCount: 289,
    category: "treatments",
    shortDescription: "Gentle AHA + PHA daily exfoliant for visibly smoother skin.",
    description: "A gentle liquid exfoliant that combines AHA (Glycolic Acid 5%, Lactic Acid 2%) and PHA (Gluconolactone 3%) to resurface skin, refine texture and boost radiance without irritation. Suitable for daily use even on sensitive skin. Enhances absorption of all subsequent skincare.",
    ingredients: "Aqua, Glycolic Acid 5%, Gluconolactone (PHA) 3%, Lactic Acid 2%, Niacinamide 3%, Panthenol, Rosa Damascena (Rose) Water, Sodium PCA, Allantoin, Glycerin",
    howToUse: "Saturate a cotton pad and sweep across clean face and neck morning or evening after cleansing. Start 3× per week, increase to daily as skin adjusts. Always apply SPF in the morning. Do not use with other exfoliants.",
    benefits: ["Smooths skin texture", "Fades dullness", "Boosts product absorption", "Gentle enough for daily use"],
    skinType: ["Normal", "Oily", "Combination", "Sensitive"],
    volume: ["100ml", "150ml"],
    gradient: "from-[#4A1F7A] via-[#2D1854] to-[#C97B3A]",
    inStock: true,
    isNew: false,
    isSale: false,
    reviews: [
      { name: "Grace L.", location: "Dublin, IE", rating: 5, date: "3 weeks ago", text: "My skin texture has improved dramatically since using this daily. It's like a gentle peel every morning.", verified: true },
      { name: "Nia J.", location: "Lagos, NG", rating: 4, date: "1 month ago", text: "Very effective at smoothing rough patches. Love that it doesn't irritate my sensitive skin.", verified: true },
      { name: "Hana M.", location: "Osaka, JP", rating: 5, date: "1 month ago", text: "Perfect toner. Light, effective, and makes my other products absorb so much better.", verified: true },
      { name: "Luna V.", location: "Buenos Aires, AR", rating: 5, date: "2 months ago", text: "Best exfoliating toner I've tried. Gentle but genuinely effective.", verified: true },
      { name: "Ivy C.", location: "Vancouver, CA", rating: 4, date: "2 months ago", text: "Great results on uneven texture. Subtle tingle which I find reassuring.", verified: true },
      { name: "Mara S.", location: "Prague, CZ", rating: 5, date: "3 months ago", text: "Skin is noticeably brighter and smoother after 2 weeks. Love this.", verified: true },
    ],
  },
  {
    id: "spf-fluid",
    name: "Botanical SPF 50 Fluid",
    subtitle: "50ml · Daily Protection",
    price: 52,
    comparePrice: null,
    badge: "New",
    badgeColor: "gold",
    rating: 4.9,
    reviewCount: 178,
    category: "moisturisers",
    shortDescription: "Featherlight mineral SPF 50 with zero white cast.",
    description: "A featherlight mineral SPF 50 fluid that provides broad-spectrum UVA and UVB protection with absolutely no white cast on any skin tone. Enriched with Antioxidant Vitamin E, Green Tea extract and Hyaluronic Acid for a hydrating, skin-protecting finish that wears beautifully under makeup.",
    ingredients: "Zinc Oxide 18%, Titanium Dioxide 5%, Aqua, Tocopherol (Vitamin E), Camellia Sinensis Leaf Extract (Green Tea), Niacinamide 3%, Sodium Hyaluronate, Cyclopentasiloxane, Dimethicone",
    howToUse: "Apply generously as the final step of your morning skincare routine. Use 1/4 teaspoon for face and neck. Reapply every 2 hours in direct sun exposure. Suitable for all skin tones — no white cast formula.",
    benefits: ["SPF 50 broad-spectrum", "Zero white cast", "Hydrating formula", "Sits perfectly under makeup"],
    skinType: ["All skin types", "Sensitive", "Acne-prone"],
    volume: ["30ml", "50ml"],
    gradient: "from-[#1A0A2E] via-[#2D1854] to-[#4A1F7A]",
    inStock: true,
    isNew: true,
    isSale: false,
    reviews: [
      { name: "Zara M.", location: "Nairobi, KE", rating: 5, date: "2 weeks ago", text: "Finally a mineral SPF with zero white cast on my deep skin tone. This is genuinely groundbreaking.", verified: true },
      { name: "Tara B.", location: "Dublin, IE", rating: 5, date: "3 weeks ago", text: "Wears beautifully under foundation. No pilling, no cast. Just perfect skin protection.", verified: true },
      { name: "Nina P.", location: "São Paulo, BR", rating: 5, date: "1 month ago", text: "The best SPF I have used at any price point. Lightweight, hydrating, no cast at all.", verified: true },
      { name: "Layla H.", location: "Cairo, EG", rating: 5, date: "1 month ago", text: "Works beautifully on my medium skin tone. No greasiness, no white cast. Perfect.", verified: true },
      { name: "Clara W.", location: "Vienna, AT", rating: 4, date: "2 months ago", text: "Very impressed. Light texture and good protection. My skin doesn't feel heavy at all.", verified: true },
      { name: "Yara N.", location: "Beirut, LB", rating: 5, date: "2 months ago", text: "Perfect last step to my morning routine. Skin looks and feels protected without any residue.", verified: true },
    ],
  },
  {
    id: "ritual-set",
    name: "Complete Ritual Gift Set",
    subtitle: "5-piece set · Save $67",
    price: 145,
    comparePrice: 212,
    badge: "Bundle",
    badgeColor: "bundle",
    rating: 5.0,
    reviewCount: 94,
    category: "gift-sets",
    shortDescription: "All 5 hero products in a luxury gift box. Save $67.",
    description: "The ultimate Lumina experience. This beautifully curated set brings together our five hero products — Glow Serum 30ml, Velvet Moisture Cream 50ml, Rose Gold Eye Elixir 15ml, Purifying Clay Masque 75ml and Silk Exfoliating Toner 150ml — presented in a signature luxury gift box with ribbon and personalised message card.",
    ingredients: "Contains all 5 Lumina hero products. Full ingredients available on individual product pages.",
    howToUse: "Morning: Silk Toner → Glow Serum → Eye Elixir → Velvet Cream → SPF. Evening: Silk Toner → Glow Serum → Eye Elixir → Velvet Cream. Full instructions card included in box.",
    benefits: ["Save $67 vs buying separately", "Complete morning + evening routine", "Luxury gift packaging", "Personalised message card"],
    skinType: ["All skin types"],
    volume: ["Full Set"],
    gradient: "from-[#C97B3A] via-[#4A1F7A] to-[#1A0A2E]",
    inStock: true,
    isNew: false,
    isSale: false,
    reviews: [
      { name: "Victoria S.", location: "London, UK", rating: 5, date: "1 week ago", text: "Bought this as a gift and the packaging alone was worth every penny. Absolutely stunning presentation.", verified: true },
      { name: "Sophia L.", location: "Monaco", rating: 5, date: "2 weeks ago", text: "Bought for myself and zero regrets. Having all 5 products together changed my skin completely.", verified: true },
      { name: "Claire D.", location: "Lyon, FR", rating: 5, date: "1 month ago", text: "Perfect gift set. Beautifully packaged and every single product is exceptional.", verified: true },
      { name: "Anna B.", location: "Warsaw, PL", rating: 5, date: "1 month ago", text: "The gift packaging is truly luxurious. Received as a birthday gift and immediately ordered one for myself.", verified: true },
      { name: "Kate M.", location: "Edinburgh, UK", rating: 5, date: "2 months ago", text: "Complete skin transformation in a box. Three months in and I look 5 years younger.", verified: true },
      { name: "Nadia F.", location: "Casablanca, MA", rating: 5, date: "2 months ago", text: "Exceptional value when you see the quality of all 5 products. Could not recommend more highly.", verified: true },
    ],
  },
  {
    id: "luminance-oil",
    name: "Luminance Facial Oil",
    subtitle: "30ml · Nourishing Radiance",
    price: 78,
    comparePrice: null,
    badge: "New",
    badgeColor: "gold",
    rating: 4.9,
    reviewCount: 203,
    category: "serums",
    shortDescription: "Dry oil blend of 7 botanicals for overnight skin transformation.",
    description: "A luxurious dry facial oil that absorbs instantly without greasiness. Blends seven cold-pressed botanical oils — Rosehip, Sea Buckthorn, Marula, Argan, Jojoba, Squalane and Cacay — to deeply nourish, firm and restore overnight radiance. Wakes up to visibly smoother, more luminous skin.",
    ingredients: "Rosa Canina Seed Oil (Rosehip), Hippophae Rhamnoides Fruit Oil (Sea Buckthorn), Sclerocarya Birrea Seed Oil (Marula), Argania Spinosa Kernel Oil (Argan), Simmondsia Chinensis Seed Oil (Jojoba), Squalane, Caryodendron Orinocense Seed Oil (Cacay), Tocopherol",
    howToUse: "Warm 3–5 drops between palms and press gently into clean skin every evening as the final step. Can be mixed with moisturiser. Absorbs fully within 60 seconds.",
    benefits: ["Absorbs instantly — no residue", "Firms and plumps overnight", "7 cold-pressed botanicals", "Suitable for all skin types"],
    skinType: ["Normal", "Dry", "Mature", "Combination"],
    volume: ["15ml", "30ml"],
    gradient: "from-[#C97B3A] via-[#4A1F7A] to-[#1A0A2E]",
    inStock: true, isNew: true, isSale: false,
    reviews: [
      { name: "Isabelle D.", location: "Paris, FR", rating: 5, date: "1 week ago", text: "I wake up glowing every single morning. This oil is extraordinary — rich yet absorbs completely in seconds.", verified: true },
      { name: "Riya S.", location: "Mumbai, IN", rating: 5, date: "2 weeks ago", text: "Finally a facial oil that doesn't leave me greasy. My skin looks genuinely radiant the next morning.", verified: true },
      { name: "Sofia A.", location: "Athens, GR", rating: 5, date: "1 month ago", text: "Three weeks in and my dry patches have completely vanished. Life-changing product.", verified: true },
      { name: "Mia W.", location: "Zürich, CH", rating: 4, date: "1 month ago", text: "Beautiful oil. Lightweight and effective. My skin tone has evened out noticeably.", verified: true },
      { name: "Chiara B.", location: "Rome, IT", rating: 5, date: "2 months ago", text: "Best facial oil I have ever used and I have tried many. The results are simply remarkable.", verified: true },
      { name: "Anna L.", location: "Helsinki, FI", rating: 5, date: "2 months ago", text: "Perfect for my dry Scandinavian winters. Skin stays nourished and soft all day long.", verified: true },
    ],
  },
  {
    id: "peptide-serum",
    name: "Pro-Age Peptide Serum",
    subtitle: "30ml · Anti-Ageing",
    price: 95,
    comparePrice: 120,
    badge: "Best Seller",
    badgeColor: "violet",
    rating: 4.9,
    reviewCount: 445,
    category: "serums",
    shortDescription: "Clinical-strength Peptide Complex reduces wrinkles by 42% in 8 weeks.",
    description: "Our most advanced anti-ageing formula. A clinical-strength serum featuring Matrixyl 3000, Argireline and Leuphasyl Peptide Complex alongside Retinol Alternative Bakuchiol to visibly reduce the appearance of fine lines and deep wrinkles. Skin feels firmer, plumper and more youthful from the first week.",
    ingredients: "Aqua, Palmitoyl Tripeptide-1 (Matrixyl), Palmitoyl Tetrapeptide-7 (Matrixyl), Acetyl Hexapeptide-3 (Argireline), Leuphasyl, Bakuchiol 1%, Sodium Hyaluronate, Niacinamide 5%, Glycerin, Panthenol",
    howToUse: "Apply 3–4 drops to clean face and neck every evening before moisturiser. For best results use consistently for a minimum of 8 weeks. Suitable for use from age 30+.",
    benefits: ["42% wrinkle reduction in 8 weeks", "Firms and plumps skin", "Clinical-strength peptides", "Retinol-free formula"],
    skinType: ["Normal", "Dry", "Mature", "Combination", "Sensitive"],
    volume: ["15ml", "30ml", "50ml"],
    gradient: "from-[#2D1854] via-[#C97B3A] to-[#1A0A2E]",
    inStock: true, isNew: false, isSale: true,
    reviews: [
      { name: "Margaret H.", location: "London, UK", rating: 5, date: "2 weeks ago", text: "At 54 I have tried every anti-ageing serum available. This is genuinely the most effective I have found.", verified: true },
      { name: "Catherine M.", location: "Lyon, FR", rating: 5, date: "1 month ago", text: "My forehead lines have visibly softened after 6 weeks. My dermatologist even noticed.", verified: true },
      { name: "Linda B.", location: "Toronto, CA", rating: 5, date: "1 month ago", text: "Remarkable firmness improvement in just 4 weeks. My jawline looks more defined.", verified: true },
      { name: "Susan K.", location: "Boston, USA", rating: 4, date: "2 months ago", text: "Real results on deep lines around my eyes. Takes commitment but absolutely worth it.", verified: true },
      { name: "Patricia W.", location: "Melbourne, AU", rating: 5, date: "2 months ago", text: "My skin looks 8 years younger. I have been stopped and asked what I use. The answer is always this serum.", verified: true },
      { name: "Helen A.", location: "Dublin, IE", rating: 5, date: "3 months ago", text: "Best investment in my skin I have ever made. Consistent visible results month after month.", verified: true },
    ],
  },
  {
    id: "barrier-balm",
    name: "Skin Barrier Repair Balm",
    subtitle: "50ml · Intensive Repair",
    price: 62,
    comparePrice: null,
    badge: "New",
    badgeColor: "gold",
    rating: 4.8,
    reviewCount: 167,
    category: "moisturisers",
    shortDescription: "Restores compromised skin barrier overnight with Ceramides + Centella.",
    description: "An intensive repair balm formulated for damaged, sensitised and compromised skin barriers. A rich yet non-occlusive formula combining Ceramide Complex, Centella Asiatica 5%, Madecassoside and Panthenol to rapidly calm redness, repair moisture loss and rebuild the skin barrier within 72 hours.",
    ingredients: "Aqua, Centella Asiatica Extract 5%, Madecassoside 1%, Ceramide NP, Ceramide AP, Ceramide EOP, Panthenol (Vitamin B5), Allantoin, Glycerin, Squalane, Shea Butter, Beta-Glucan",
    howToUse: "Apply generously to clean skin morning and evening. Can be used as an intensive overnight mask 2–3 times per week. Ideal for skin recovering from over-exfoliation, retinol or professional treatments.",
    benefits: ["Repairs barrier in 72 hours", "Instantly calms redness", "Non-occlusive formula", "Safe for post-treatment skin"],
    skinType: ["Sensitive", "Dry", "Damaged", "All types"],
    volume: ["30ml", "50ml"],
    gradient: "from-[#4A1F7A] via-[#1A0A2E] to-[#2D1854]",
    inStock: true, isNew: true, isSale: false,
    reviews: [
      { name: "Ava M.", location: "New York, USA", rating: 5, date: "1 week ago", text: "My eczema-prone skin has never been so calm. This balm is a miracle for sensitive skin.", verified: true },
      { name: "Lara K.", location: "Berlin, DE", rating: 5, date: "2 weeks ago", text: "After over-exfoliating my skin this rescued it completely within 3 days. Incredible product.", verified: true },
      { name: "Nour A.", location: "Amman, JO", rating: 5, date: "1 month ago", text: "My redness and sensitivity has reduced dramatically. This is now my most essential product.", verified: true },
      { name: "Elena V.", location: "Athens, GR", rating: 4, date: "1 month ago", text: "Very soothing and calming. My reactive skin tolerates this perfectly.", verified: true },
      { name: "Freya L.", location: "Oslo, NO", rating: 5, date: "2 months ago", text: "Perfect for harsh winter weather. Skin barrier restored and maintained all season.", verified: true },
      { name: "Mira J.", location: "Prague, CZ", rating: 5, date: "2 months ago", text: "Finally found something that actually works on my compromised barrier. Worth every penny.", verified: true },
    ],
  },
  {
    id: "vitamin-c-mask",
    name: "Radiance Vitamin C Mask",
    subtitle: "75ml · Brightening Treatment",
    price: 48,
    comparePrice: 60,
    badge: "Sale",
    badgeColor: "sale",
    rating: 4.7,
    reviewCount: 312,
    category: "treatments",
    shortDescription: "10-minute brightening mask with 20% Vitamin C + Turmeric.",
    description: "A potent leave-on brightening mask with a high-dose Vitamin C 20% and Turmeric extract to visibly correct uneven skin tone, dark spots and post-acne marks in a single 10-minute treatment. Use weekly for a cumulative brightening effect that rivals professional facials.",
    ingredients: "Aqua, Ascorbic Acid (Vitamin C) 20%, Curcuma Longa (Turmeric) Root Extract, Kaolin, Alpha-Arbutin 2%, Niacinamide 5%, Glycerin, Allantoin, Lactic Acid 3%",
    howToUse: "Apply a generous layer to clean skin once or twice weekly. Leave for 10–15 minutes. Rinse with warm water. Follow with moisturiser and SPF in the morning. Avoid eye area.",
    benefits: ["High-dose 20% Vitamin C", "Visibly corrects dark spots", "Professional results at home", "Suitable for weekly use"],
    skinType: ["Normal", "Oily", "Combination", "Hyperpigmented"],
    volume: ["75ml"],
    gradient: "from-[#C97B3A] via-[#2D1854] to-[#4A1F7A]",
    inStock: true, isNew: false, isSale: true,
    reviews: [
      { name: "Keisha T.", location: "Atlanta, USA", rating: 5, date: "3 weeks ago", text: "My post-acne marks have faded significantly after 4 weekly uses. Results are genuinely impressive.", verified: true },
      { name: "Yui N.", location: "Kyoto, JP", rating: 5, date: "1 month ago", text: "My skin tone is so much more even. I use this every Sunday and look forward to it every week.", verified: true },
      { name: "Adaeze O.", location: "Abuja, NG", rating: 5, date: "1 month ago", text: "The best treatment for hyperpigmentation I have ever used. My dark spots are almost completely gone.", verified: true },
      { name: "Bianca R.", location: "Rio, BR", rating: 4, date: "2 months ago", text: "Really noticeable brightening. Slight tingle which shows it is working.", verified: true },
      { name: "Ji Y.", location: "Seoul, KR", rating: 5, date: "2 months ago", text: "Glass skin in a jar. My complexion is completely transformed after 6 weekly uses.", verified: true },
      { name: "Amara D.", location: "Dakar, SN", rating: 5, date: "3 months ago", text: "Uneven skin tone is my main concern and this addresses it better than anything else I have tried.", verified: true },
    ],
  },
  {
    id: "duo-ritual-set",
    name: "Morning & Night Duo Set",
    subtitle: "2-piece set · Save $28",
    price: 115,
    comparePrice: 143,
    badge: "Bundle",
    badgeColor: "bundle",
    rating: 4.9,
    reviewCount: 156,
    category: "gift-sets",
    shortDescription: "The perfect AM + PM routine in one gift set. Save $28.",
    description: "The ultimate daily ritual, perfectly paired. This duo set brings together the Lumina Glow Serum for your morning routine and the Pro-Age Peptide Serum for your evening routine — the two most powerful active treatments in our range, presented in a signature gift box with AM/PM routine card.",
    ingredients: "Contains full ingredient lists of Lumina Glow Serum 30ml and Pro-Age Peptide Serum 30ml.",
    howToUse: "AM: Glow Serum after cleansing, before moisturiser and SPF. PM: Peptide Serum after cleansing, before moisturiser. Full AM/PM routine card included in box.",
    benefits: ["Complete AM + PM routine", "Save $28 vs buying separately", "Luxury gift packaging", "AM/PM routine guide card"],
    skinType: ["All skin types"],
    volume: ["2-Piece Set"],
    gradient: "from-[#1A0A2E] via-[#C97B3A] to-[#2D1854]",
    inStock: true, isNew: false, isSale: false,
    reviews: [
      { name: "Rachel G.", location: "Singapore", rating: 5, date: "2 weeks ago", text: "The perfect introduction to Lumina. Using both serums morning and evening has completely transformed my skin.", verified: true },
      { name: "Dina F.", location: "Kuwait City", rating: 5, date: "1 month ago", text: "Gifted this to my sister and she called me crying happy tears. The packaging is stunning.", verified: true },
      { name: "Serena W.", location: "Toronto, CA", rating: 5, date: "1 month ago", text: "Having a dedicated AM and PM serum has made my routine feel so luxurious. Results are incredible.", verified: true },
      { name: "Mia K.", location: "Copenhagen, DK", rating: 5, date: "2 months ago", text: "The most thoughtful skincare gift set I have received. Both serums are exceptional.", verified: true },
      { name: "Aria L.", location: "Shanghai, CN", rating: 4, date: "2 months ago", text: "Beautiful set. The AM serum brightens and the PM serum firms. Perfect combination.", verified: true },
      { name: "Petra S.", location: "Budapest, HU", rating: 5, date: "3 months ago", text: "Bought as a self-gift and best decision I ever made. Remarkable skin transformation.", verified: true },
    ],
  },
];

export const collections = [
  { id: "serums",       name: "Serums",       description: "Targeted active treatments",  count: 4, heroGradient: "from-[#1A0A2E] via-[#2D1854] to-[#C97B3A]", cardGradient: "from-[#1A0A2E] via-[#2D1854] to-[#C97B3A]", icon: "💧" },
  { id: "moisturisers", name: "Moisturisers", description: "Deep hydration formulas",     count: 3, heroGradient: "from-[#2D1854] via-[#4A1F7A] to-[#C97B3A]", cardGradient: "from-[#2D1854] via-[#4A1F7A] to-[#C97B3A]", icon: "🫧" },
  { id: "treatments",   name: "Treatments",   description: "Exfoliate and purify",        count: 3, heroGradient: "from-[#1A0A2E] via-[#2D1854] to-[#4A1F7A]", cardGradient: "from-[#1A0A2E] via-[#2D1854] to-[#4A1F7A]", icon: "✨" },
  { id: "gift-sets",    name: "Gift Sets",    description: "Curated luxury collections",  count: 2, heroGradient: "from-[#1A0A2E] via-[#4A1F7A] to-[#C97B3A]", cardGradient: "from-[#1A0A2E] via-[#4A1F7A] to-[#C97B3A]", icon: "🎁" },
];

export const faqs = [
  { category: "Shipping", question: "How long does standard delivery take?", answer: "Standard delivery takes 3–5 business days within the US and 5–10 business days internationally. Express 1–2 day shipping is available at checkout for an additional fee." },
  { category: "Shipping", question: "Do you offer free shipping?", answer: "Yes. All orders over $60 qualify for complimentary standard shipping. Orders under $60 have a flat shipping fee of $5.99 within the US." },
  { category: "Shipping", question: "Do you ship internationally?", answer: "We ship to over 40 countries worldwide. International shipping costs and estimated delivery times are calculated at checkout based on your destination." },
  { category: "Returns", question: "What is your return policy?", answer: "We offer a 30-day money-back guarantee on all products. If you are not completely satisfied for any reason, contact our team and we will arrange a full refund or exchange at no cost to you." },
  { category: "Returns", question: "How do I start a return?", answer: "Email returns@lumina.com with your order number and reason for return. We will send you a prepaid return shipping label within 24 hours." },
  { category: "Returns", question: "Can I return opened products?", answer: "Yes. We accept returns of opened products within 30 days of purchase provided at least 70% of the product remains. We stand behind the effectiveness of every formula." },
  { category: "Products", question: "Are your products suitable for sensitive skin?", answer: "All Lumina products are dermatologist-tested and formulated without parabens, sulfates, synthetic fragrances or known irritants. Most products in our range are suitable for sensitive skin — check individual product pages for specific guidance." },
  { category: "Products", question: "Are you cruelty-free and vegan?", answer: "Yes, completely. Lumina is certified 100% cruelty-free and all products are vegan. We never test on animals at any stage of production and use no animal-derived ingredients whatsoever." },
  { category: "Products", question: "Can I use multiple Lumina products together?", answer: "Absolutely — our range is designed to work synergistically. The recommended layering order is: Toner → Serum → Eye Elixir → Moisturiser → SPF (morning only). Thinnest to thickest consistency." },
  { category: "Subscriptions", question: "How does Subscribe & Save work?", answer: "Subscribe to any product to receive a 20% discount on every order. Choose your preferred delivery frequency — every 4, 6 or 8 weeks — and cancel, pause or modify at any time with no fees or penalties." },
  { category: "Subscriptions", question: "Can I change my subscription frequency?", answer: "Yes. Log into your account at any time to change delivery frequency, swap products, pause for up to 3 months or cancel your subscription. Changes take effect on your next scheduled order." },
  { category: "Subscriptions", question: "When will my subscription renew?", answer: "You will receive an email reminder 3 days before your next order is processed. Payment is taken on your renewal date and tracking information is emailed as soon as your order is dispatched." },
];
